import type {
  Bird,
  MarketplaceListing,
  TimelineEvent,
  Club,
  NewsArticle,
  RankingEntry,
  Owner,
  Event,
} from "@/types";

// Ảnh cu gáy (Spotted Dove - Spilopelia chinensis) thật từ Wikimedia Commons
const BIRD_IMAGES = [
  // Cu gáy đậu cành - màu đặc trưng nâu đốm trắng
  "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Streptopelia_chinensis_-_Ang_Mo_Kio.jpg/800px-Streptopelia_chinensis_-_Ang_Mo_Kio.jpg",
  // Cu gáy trong tự nhiên - Ấn Độ
  "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Spotted_dove_on_the_grass_-_Flickr_-_Lip_Kee.jpg/800px-Spotted_dove_on_the_grass_-_Flickr_-_Lip_Kee.jpg",
  // Cu gáy đứng - góc đẹp
  "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Spotted_Dove_at_Tennoji_Park.JPG/800px-Spotted_Dove_at_Tennoji_Park.JPG",
  // Cu gáy cận cảnh - rõ đốm đặc trưng
  "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Spotted_dove_%28Spilopelia_chinensis%29_Photograph_By_Shantanu_Kuveskar.jpg/800px-Spotted_dove_%28Spilopelia_chinensis%29_Photograph_By_Shantanu_Kuveskar.jpg",
  // Cu gáy mái nhà - tự nhiên
  "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Spotted_Dove_I_IMG_8493.jpg/800px-Spotted_Dove_I_IMG_8493.jpg",
  // Cu gáy đậu nhánh - lông đẹp
  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Spotted_dove_%28Spilopelia_chinensis_tigrina%29.jpg/800px-Spotted_dove_%28Spilopelia_chinensis_tigrina%29.jpg",
];

const AVATARS = [
  "https://i.pravatar.cc/150?img=1",
  "https://i.pravatar.cc/150?img=2",
  "https://i.pravatar.cc/150?img=3",
  "https://i.pravatar.cc/150?img=4",
  "https://i.pravatar.cc/150?img=5",
  "https://i.pravatar.cc/150?img=6",
  "https://i.pravatar.cc/150?img=7",
  "https://i.pravatar.cc/150?img=8",
];

export const MOCK_BIRDS: Bird[] = [
  {
    id: "bird-001",
    name: "Dũng Sĩ Tây Đô",
    slug: "dung-si-tay-do",
    ownerId: "user-001",
    ownerName: "Nguyễn Văn Mạnh",
    ownerAvatar: AVATARS[0],
    voice: "Thổ",
    age: 5,
    origin: "Cần Thơ",
    province: "Cần Thơ",
    image: BIRD_IMAGES[0],
    gallery: BIRD_IMAGES.slice(0, 4),
    achievements: ["Vô địch miền Tây 2023", "Á quân toàn quốc 2022", "Top 3 giải Xuân 2024"],
    description: "Dũng Sĩ Tây Đô là một trong những chiến binh cu gáy xuất sắc nhất miền Tây. Giọng thổ đặc trưng, mạnh mẽ và trường hơi, đã qua nhiều kỳ thi đấu cấp khu vực và toàn quốc.",
    rating: 4.9,
    followers: 2340,
    videoCount: 48,
    verified: true,
    views: 18900,
    likes: 4200,
    price: 85000000,
    forSale: false,
    createdAt: "2020-03-15",
    lineage: "Dòng Tây Đô",
    weight: "185g",
    color: "Xanh lam + Nâu đỏ",
    rank: 1,
    score: 9850,
  },
  {
    id: "bird-002",
    name: "Chiến Binh Hà Thành",
    slug: "chien-binh-ha-thanh",
    ownerId: "user-002",
    ownerName: "Trần Đức Long",
    ownerAvatar: AVATARS[1],
    voice: "Vàng",
    age: 3,
    origin: "Hà Nội",
    province: "Hà Nội",
    image: BIRD_IMAGES[1],
    gallery: BIRD_IMAGES.slice(1, 5),
    achievements: ["Quán quân giải Thủ Đô 2024", "Top 5 Bắc Bộ 2023"],
    description: "Giọng vàng trong trẻo, lanh lợi. Chiến Binh Hà Thành nổi tiếng với phong cách đấu chủ động và giọng gáy vang xa.",
    rating: 4.7,
    followers: 1820,
    videoCount: 31,
    verified: true,
    views: 12400,
    likes: 2900,
    price: 55000000,
    forSale: true,
    createdAt: "2022-08-20",
    lineage: "Dòng Bắc Bộ",
    weight: "172g",
    color: "Xám bạc + Trắng",
    rank: 2,
    score: 9200,
  },
  {
    id: "bird-003",
    name: "Kim Cương Đà Lạt",
    slug: "kim-cuong-da-lat",
    ownerId: "user-003",
    ownerName: "Lê Hoàng Phúc",
    ownerAvatar: AVATARS[2],
    voice: "Kim",
    age: 4,
    origin: "Đà Lạt",
    province: "Lâm Đồng",
    image: BIRD_IMAGES[2],
    gallery: BIRD_IMAGES.slice(2, 6),
    achievements: ["Vô địch Tây Nguyên 2023", "Hạng 3 toàn quốc 2023"],
    description: "Giọng kim trong vắt, hiếm có. Được nuôi dưỡng trong điều kiện khí hậu mát mẻ Đà Lạt, Kim Cương sở hữu sức bền phi thường.",
    rating: 4.8,
    followers: 1560,
    videoCount: 27,
    verified: true,
    views: 9800,
    likes: 2100,
    price: 70000000,
    forSale: false,
    createdAt: "2021-05-10",
    lineage: "Dòng Cao Nguyên",
    weight: "178g",
    color: "Vàng đất + Nâu",
    rank: 3,
    score: 8900,
  },
  {
    id: "bird-004",
    name: "Thần Ưng Sài Gòn",
    slug: "than-ung-sai-gon",
    ownerId: "user-004",
    ownerName: "Phạm Quốc Tuấn",
    ownerAvatar: AVATARS[3],
    voice: "Đấu",
    age: 6,
    origin: "TP. Hồ Chí Minh",
    province: "TP. Hồ Chí Minh",
    image: BIRD_IMAGES[3],
    gallery: BIRD_IMAGES,
    achievements: ["5 lần vô địch TP.HCM", "Vô địch miền Nam 2022", "Quán quân toàn quốc 2021"],
    description: "Huyền thoại của làng cu gáy miền Nam. Thần Ưng Sài Gòn có bộ lông đẹp nhất và giọng đấu mạnh nhất trong 5 năm gần đây.",
    rating: 5.0,
    followers: 5420,
    videoCount: 92,
    verified: true,
    views: 45600,
    likes: 12000,
    forSale: false,
    createdAt: "2019-01-20",
    lineage: "Dòng Nam Bộ",
    weight: "195g",
    color: "Xanh đen + Tím",
    rank: 4,
    score: 8600,
  },
  {
    id: "bird-005",
    name: "Ngọc Trai Xứ Huế",
    slug: "ngoc-trai-xu-hue",
    ownerId: "user-005",
    ownerName: "Hoàng Minh Tuấn",
    ownerAvatar: AVATARS[4],
    voice: "Thủy",
    age: 2,
    origin: "Huế",
    province: "Thừa Thiên Huế",
    image: BIRD_IMAGES[4],
    gallery: BIRD_IMAGES.slice(0, 3),
    achievements: ["Hạng nhì giải miền Trung 2024"],
    description: "Giọng thủy mượt mà, êm dịu. Ngọc Trai mới gia nhập làng đấu nhưng đã gây tiếng vang lớn với phong cách gáy tinh tế.",
    rating: 4.5,
    followers: 890,
    videoCount: 15,
    verified: false,
    views: 5200,
    likes: 980,
    price: 25000000,
    forSale: true,
    createdAt: "2023-11-01",
    lineage: "Dòng Miền Trung",
    weight: "165g",
    color: "Trắng ngà + Xanh nhạt",
    rank: 5,
    score: 7800,
  },
  {
    id: "bird-006",
    name: "Bạch Ngọc Đà Nẵng",
    slug: "bach-ngoc-da-nang",
    ownerId: "user-006",
    ownerName: "Võ Thanh Hải",
    ownerAvatar: AVATARS[5],
    voice: "Đồng",
    age: 3,
    origin: "Đà Nẵng",
    province: "Đà Nẵng",
    image: BIRD_IMAGES[5],
    gallery: BIRD_IMAGES.slice(3, 6),
    achievements: ["Top 1 Đà Nẵng 2023", "Hạng ba miền Trung 2023"],
    description: "Giọng đồng vang rền, ổn định. Bạch Ngọc là niềm tự hào của người chơi cu gáy xứ Đà thành.",
    rating: 4.6,
    followers: 1240,
    videoCount: 22,
    verified: true,
    views: 7800,
    likes: 1650,
    price: 42000000,
    forSale: true,
    createdAt: "2022-03-18",
    lineage: "Dòng Duyên Hải",
    weight: "180g",
    color: "Trắng thuần",
    rank: 6,
    score: 7500,
  },
];

export const MOCK_MARKETPLACE: MarketplaceListing[] = [
  {
    id: "list-001",
    birdId: "bird-002",
    birdName: "Chiến Binh Hà Thành",
    birdImage: BIRD_IMAGES[1],
    sellerId: "user-002",
    sellerName: "Trần Đức Long",
    sellerAvatar: AVATARS[1],
    price: 55000000,
    province: "Hà Nội",
    voice: "Vàng",
    age: 3,
    negotiable: true,
    views: 1240,
    postedAt: "2025-05-28T08:00:00Z",
    description: "Bán chim cu gáy giống Vàng, 3 tuổi, đã thi đấu nhiều giải cấp tỉnh và khu vực. Chim khỏe mạnh, lông đẹp, giọng trong. Có hồ sơ xác thực đầy đủ.",
    verified: true,
  },
  {
    id: "list-002",
    birdId: "bird-005",
    birdName: "Ngọc Trai Xứ Huế",
    birdImage: BIRD_IMAGES[4],
    sellerId: "user-005",
    sellerName: "Hoàng Minh Tuấn",
    sellerAvatar: AVATARS[4],
    price: 25000000,
    province: "Thừa Thiên Huế",
    voice: "Thủy",
    age: 2,
    negotiable: false,
    views: 890,
    postedAt: "2025-05-30T10:00:00Z",
    description: "Chim non 2 tuổi, giọng Thủy thuần chủng. Phù hợp cho người mới chơi muốn tập huấn. Có thể giao lưu trực tiếp tại Huế.",
    verified: false,
  },
  {
    id: "list-003",
    birdId: "bird-006",
    birdName: "Bạch Ngọc Đà Nẵng",
    birdImage: BIRD_IMAGES[5],
    sellerId: "user-006",
    sellerName: "Võ Thanh Hải",
    sellerAvatar: AVATARS[5],
    price: 42000000,
    province: "Đà Nẵng",
    voice: "Đồng",
    age: 3,
    negotiable: true,
    views: 2100,
    postedAt: "2025-05-25T14:00:00Z",
    description: "Bán hoặc trao đổi chim cu gáy Bạch Ngọc. Giọng Đồng đẳng cấp, lông trắng hiếm có. Đã đoạt giải Top 1 Đà Nẵng 2023.",
    verified: true,
  },
  {
    id: "list-004",
    birdId: "bird-new-01",
    birdName: "Hổ Phụ Cần Thơ",
    birdImage: BIRD_IMAGES[0],
    sellerId: "user-007",
    sellerName: "Nguyễn Thành Danh",
    sellerAvatar: AVATARS[6],
    price: 18000000,
    province: "Cần Thơ",
    voice: "Thổ",
    age: 2,
    negotiable: true,
    views: 430,
    postedAt: "2025-05-31T09:00:00Z",
    description: "Chim non tiềm năng, dòng Thổ chính gốc Tây Đô. Đang trong quá trình tập luyện, có thể phát triển thành chiến binh xuất sắc.",
    verified: false,
  },
  {
    id: "list-005",
    birdId: "bird-new-02",
    birdName: "Long Thần Khánh Hòa",
    birdImage: BIRD_IMAGES[2],
    sellerId: "user-008",
    sellerName: "Lê Văn Phú",
    sellerAvatar: AVATARS[7],
    price: 35000000,
    province: "Khánh Hòa",
    voice: "Kim",
    age: 4,
    negotiable: false,
    views: 780,
    postedAt: "2025-05-27T11:00:00Z",
    description: "Chim cu gáy Kim thuần chủng từ Khánh Hòa. Giọng kim cao vút, ổn định. Đã qua kiểm định y tế đầy đủ.",
    verified: true,
  },
  {
    id: "list-006",
    birdId: "bird-new-03",
    birdName: "Phượng Hoàng Nghệ An",
    birdImage: BIRD_IMAGES[3],
    sellerId: "user-009",
    sellerName: "Trần Quốc Bảo",
    sellerAvatar: AVATARS[0],
    price: 60000000,
    province: "Nghệ An",
    voice: "Đấu",
    age: 5,
    negotiable: true,
    views: 1560,
    postedAt: "2025-05-24T16:00:00Z",
    description: "Chiến binh Đấu dày dạn kinh nghiệm. 5 tuổi, đã thi đấu 12 giải từ cấp huyện đến cấp tỉnh. Cần chủ nhân mới xứng tầm.",
    verified: true,
  },
];

export const MOCK_TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: "evt-001",
    birdId: "bird-001",
    date: "2020-03-15",
    title: "Bắt đầu nuôi",
    description: "Dũng Sĩ Tây Đô được đón về nhà từ một trại chim uy tín tại Cần Thơ. Lúc đó chim mới được 3 tháng tuổi, lông còn mềm nhưng đã có tố chất đặc biệt.",
    type: "milestone",
    image: BIRD_IMAGES[0],
  },
  {
    id: "evt-002",
    birdId: "bird-001",
    date: "2020-09-20",
    title: "Tập mồi lần đầu",
    description: "Sau 6 tháng thuần dưỡng, bắt đầu cho chim tiếp xúc với mồi nhử trong điều kiện kiểm soát. Chim phản ứng rất tốt, bản năng săn mồi mạnh mẽ.",
    type: "training",
  },
  {
    id: "evt-003",
    birdId: "bird-001",
    date: "2021-02-10",
    title: "Bắt bổi đầu tiên",
    description: "Thành tích bắt bổi đầu tiên trong buổi tập ngoài đồng. Chim tự tin, giọng gáy vang rền thu hút nhiều con mồi trong bán kính rộng.",
    type: "milestone",
    image: BIRD_IMAGES[1],
  },
  {
    id: "evt-004",
    birdId: "bird-001",
    date: "2021-08-15",
    title: "Thay lông lần đầu",
    description: "Qua mùa thay lông thuận lợi, bộ lông mới đẹp hơn, giọng gáy trở nên ổn định và có chiều sâu hơn rõ rệt.",
    type: "health",
  },
  {
    id: "evt-005",
    birdId: "bird-001",
    date: "2022-04-20",
    title: "Á quân toàn quốc 2022",
    description: "Tham gia giải vô địch cu gáy toàn quốc tại Hà Nội, đạt thành tích Á quân - vị trí cao nhất từ trước đến nay của một chim đến từ Cần Thơ.",
    type: "award",
    image: BIRD_IMAGES[2],
  },
  {
    id: "evt-006",
    birdId: "bird-001",
    date: "2023-06-12",
    title: "Vô địch miền Tây 2023",
    description: "Đăng quang giải vô địch cu gáy miền Tây lần thứ nhất. Trận chung kết lịch sử với màn thể hiện 45 phút xuất sắc.",
    type: "award",
    image: BIRD_IMAGES[3],
  },
];

export const MOCK_CLUBS: Club[] = [
  {
    id: "club-001",
    name: "CLB Cu Gáy Tây Đô",
    province: "Cần Thơ",
    memberCount: 340,
    founded: "2015-03-10",
    logo: AVATARS[0],
    description: "Câu lạc bộ cu gáy lớn nhất miền Tây với hơn 340 thành viên tích cực. Tổ chức định kỳ hàng tháng tại công viên Ninh Kiều.",
    verified: true,
    coverImage: BIRD_IMAGES[0],
  },
  {
    id: "club-002",
    name: "CLB Cu Gáy Hà Nội",
    province: "Hà Nội",
    memberCount: 520,
    founded: "2012-08-20",
    logo: AVATARS[1],
    description: "Câu lạc bộ lớn nhất miền Bắc. Nơi quy tụ những chiến binh cu gáy xuất sắc nhất xứ Bắc, tổ chức giải hàng tuần.",
    verified: true,
    coverImage: BIRD_IMAGES[1],
  },
  {
    id: "club-003",
    name: "CLB Cu Gáy Đà Nẵng",
    province: "Đà Nẵng",
    memberCount: 210,
    founded: "2018-01-15",
    logo: AVATARS[2],
    description: "CLB trẻ năng động của miền Trung. Thường xuyên kết nối giao lưu với các CLB trong cả nước.",
    verified: true,
    coverImage: BIRD_IMAGES[2],
  },
  {
    id: "club-004",
    name: "CLB Cu Gáy Sài Gòn",
    province: "TP. Hồ Chí Minh",
    memberCount: 680,
    founded: "2010-05-20",
    logo: AVATARS[3],
    description: "CLB cu gáy đông thành viên nhất Việt Nam. Đã tổ chức hơn 200 giải đấu lớn nhỏ trong suốt 15 năm hoạt động.",
    verified: true,
    coverImage: BIRD_IMAGES[3],
  },
  {
    id: "club-005",
    name: "CLB Cu Gáy Xứ Huế",
    province: "Thừa Thiên Huế",
    memberCount: 145,
    founded: "2019-09-01",
    logo: AVATARS[4],
    description: "Nơi bảo tồn và phát triển những dòng cu gáy đặc trưng của vùng đất Cố Đô.",
    verified: false,
    coverImage: BIRD_IMAGES[4],
  },
  {
    id: "club-006",
    name: "CLB Cu Gáy Khánh Hòa",
    province: "Khánh Hòa",
    memberCount: 188,
    founded: "2017-06-10",
    logo: AVATARS[5],
    description: "CLB nổi tiếng với phong cách tổ chức chuyên nghiệp và nhiều hoạt động ngoài trời tại Nha Trang.",
    verified: true,
    coverImage: BIRD_IMAGES[5],
  },
];

export const MOCK_NEWS: NewsArticle[] = [
  {
    id: "news-001",
    title: "Giải Cu Gáy Toàn Quốc 2025: Những Chiến Binh Nào Đáng Chú Ý?",
    slug: "giai-cu-gay-toan-quoc-2025",
    excerpt: "Giải vô địch cu gáy toàn quốc 2025 sắp diễn ra với hơn 200 chú chim tham dự từ 63 tỉnh thành. Đây là sự kiện được mong chờ nhất trong năm.",
    content: "",
    coverImage: BIRD_IMAGES[0],
    author: "Biên Tập Viên CuGay.vn",
    authorAvatar: AVATARS[0],
    category: "Tin tức",
    publishedAt: "2025-05-30T08:00:00Z",
    readTime: 5,
    views: 12400,
  },
  {
    id: "news-002",
    title: "Bí Quyết Chăm Sóc Cu Gáy Mùa Hè: Tránh Nắng, Đủ Nước, Giữ Giọng",
    slug: "bi-quyet-cham-soc-cu-gay-mua-he",
    excerpt: "Mùa hè nắng nóng là thử thách lớn với chủ nuôi cu gáy. Chúng tôi tổng hợp những bí quyết từ các chuyên gia để giữ chim khỏe mạnh và duy trì giọng đấu tốt.",
    content: "",
    coverImage: BIRD_IMAGES[1],
    author: "Chuyên gia Lê Văn Thành",
    authorAvatar: AVATARS[1],
    category: "Kinh nghiệm",
    publishedAt: "2025-05-28T10:00:00Z",
    readTime: 8,
    views: 8900,
  },
  {
    id: "news-003",
    title: "CLB Cu Gáy Sài Gòn Kỷ Niệm 15 Năm Thành Lập Với Giải Đấu Đặc Biệt",
    slug: "clb-cu-gay-sai-gon-ky-niem-15-nam",
    excerpt: "Nhân dịp 15 năm thành lập, CLB Cu Gáy Sài Gòn tổ chức giải đấu đặc biệt với tổng giải thưởng lên đến 500 triệu đồng.",
    content: "",
    coverImage: BIRD_IMAGES[2],
    author: "Phóng viên Minh Nhật",
    authorAvatar: AVATARS[2],
    category: "Sự kiện",
    publishedAt: "2025-05-26T14:00:00Z",
    readTime: 4,
    views: 6700,
  },
  {
    id: "news-004",
    title: "Xu Hướng Thị Trường Cu Gáy Quý II/2025: Giá Giọng Kim Tăng Mạnh",
    slug: "thi-truong-cu-gay-quy-2-2025",
    excerpt: "Phân tích thị trường cho thấy giá chim cu gáy giọng Kim đang tăng 30% so với cùng kỳ, trong khi giọng Thổ vẫn giữ vị trí số 1.",
    content: "",
    coverImage: BIRD_IMAGES[3],
    author: "Phân tích viên Quốc Việt",
    authorAvatar: AVATARS[3],
    category: "Thị trường",
    publishedAt: "2025-05-24T09:00:00Z",
    readTime: 6,
    views: 9800,
  },
  {
    id: "news-005",
    title: "Hành Trình Của Dũng Sĩ Tây Đô: Từ Chim Non Đến Vô Địch Miền Tây",
    slug: "hanh-trinh-dung-si-tay-do",
    excerpt: "Câu chuyện cảm hứng về hành trình 3 năm của Dũng Sĩ Tây Đô từ một chú chim bình thường đến ngôi vô địch miền Tây.",
    content: "",
    coverImage: BIRD_IMAGES[4],
    author: "Nguyễn Văn Mạnh",
    authorAvatar: AVATARS[4],
    category: "Câu chuyện",
    publishedAt: "2025-05-22T11:00:00Z",
    readTime: 10,
    views: 15600,
  },
  {
    id: "news-006",
    title: "Hướng Dẫn Xây Lồng Cu Gáy Chuẩn Kỹ Thuật Cho Người Mới Bắt Đầu",
    slug: "huong-dan-xay-long-cu-gay",
    excerpt: "Lồng chim là môi trường sống quan trọng ảnh hưởng trực tiếp đến sức khỏe và giọng gáy. Bài viết hướng dẫn chi tiết cho người mới.",
    content: "",
    coverImage: BIRD_IMAGES[5],
    author: "Thợ lồng Cao Thắng",
    authorAvatar: AVATARS[5],
    category: "Hướng dẫn",
    publishedAt: "2025-05-20T15:00:00Z",
    readTime: 7,
    views: 7200,
  },
];

export const MOCK_RANKINGS: RankingEntry[] = MOCK_BIRDS.map((bird, i) => ({
  rank: i + 1,
  birdId: bird.id,
  birdName: bird.name,
  birdImage: bird.image,
  ownerId: bird.ownerId,
  ownerName: bird.ownerName,
  province: bird.province,
  score: bird.score ?? 9000 - i * 300,
  voice: bird.voice,
  achievements: bird.achievements.length,
  change: i === 0 ? "same" : i === 2 ? "up" : "down",
}));

export const MOCK_OWNERS: Owner[] = MOCK_BIRDS.map((bird, i) => ({
  id: bird.ownerId,
  name: bird.ownerName,
  avatar: bird.ownerAvatar,
  province: bird.province,
  birdCount: Math.floor(Math.random() * 8) + 1,
  joinedAt: `201${5 + i}-0${i + 1}-10`,
  verified: bird.verified,
  rank: i + 1,
  followers: bird.followers,
}));

export const MOCK_EVENTS: Event[] = [
  {
    id: "event-001",
    title: "Giải Cu Gáy Toàn Quốc 2025",
    description: "Giải đấu lớn nhất năm 2025 quy tụ hơn 200 chiến binh từ khắp 63 tỉnh thành.",
    date: "2025-07-15",
    location: "Cung Văn Hóa Lao Động TP.HCM",
    province: "TP. Hồ Chí Minh",
    organizer: "Hội Cu Gáy Việt Nam",
    image: BIRD_IMAGES[0],
    attendees: 1800,
    type: "competition",
  },
  {
    id: "event-002",
    title: "Hội Tụ Cu Gáy Miền Bắc 2025",
    description: "Sự kiện giao lưu và triển lãm chim cu gáy đặc sắc nhất miền Bắc năm 2025.",
    date: "2025-06-20",
    location: "Công Viên Thống Nhất, Hà Nội",
    province: "Hà Nội",
    organizer: "CLB Cu Gáy Hà Nội",
    image: BIRD_IMAGES[1],
    attendees: 950,
    type: "exhibition",
  },
  {
    id: "event-003",
    title: "Giao Lưu CLB Miền Trung Lần 5",
    description: "Buổi giao lưu thân thiện giữa các CLB cu gáy từ Nghệ An đến Bình Định.",
    date: "2025-06-08",
    location: "Công Viên APEC, Đà Nẵng",
    province: "Đà Nẵng",
    organizer: "CLB Cu Gáy Đà Nẵng",
    image: BIRD_IMAGES[2],
    attendees: 420,
    type: "meetup",
  },
];

export const STATS = {
  totalBirds: 12847,
  totalMembers: 38420,
  totalTransactions: 5640,
  totalClubs: 284,
};
